gps-port: 8308            ## this term is disable now
data-port: 2369           ## make sure this data-port is yours, you can check your data-port with wireshark
type: velodyneVLP16

gps: False    ## this term is disable now
text: True    ##  Ture means save Text files
ply: True    ##  Ture means save PCD files

from: 0  # first packet to read
to: -1   # last packet to read

